config/routes.rb
Rails.application.routes.draw do

  root "users#index"

  resources :users
  resource :session, only: [:new, :create, :destroy]

  resources :questions, except: [:show, :new, :index]
  resources :hashtags, only: [:show]
end

app/models/question.rb
class Question < ApplicationRecord
  validates :text, :user, presence: true

  # проверка максимальной длины текста вопроса (максимум 255 символов)
  validates :text, length: { maximum: 255 }

  belongs_to :user
  belongs_to :author, class_name: 'User', optional: true

  has_and_belongs_to_many :hashtags, join_table: :hashtags_questions, dependent: :destroy

  # добавляем к вопросу хэштеги, если они есть;
  # и удаляем хэштеги, которые не относятся больше ни к каким вопросам
  def add_hashtags
    hashtags_to_add = find_hashtags - hashtags.collect(&:text)
    hashtags_to_delete = hashtags.collect(&:text) - find_hashtags

    Hashtag.create!(self, hashtags_to_add)
    Hashtag.clear!(self, hashtags_to_delete)
  end

  # ищем хэштеги в строке и оставляем только уникальные
  def find_hashtags
    hashtag_regexp = /#[[:word:]-]+/
    (text.to_s + " " + answer.to_s).scan(hashtag_regexp).uniq
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_question, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, except: [:create]

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.author = current_user

    if check_captcha(@question) && @question.save
      @question.add_hashtags
      redirect_to user_path(@question.user), notice: 'Вопрос задан!'
    else
      render :edit
    end
  end

  def update
    if @question.update(question_params)
      @question.add_hashtags
      redirect_to user_path(@question.user), notice: 'Вопрос сохранен!'
    else
      render :edit
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    user = @question.user
    @question.destroy
    redirect_to user_path(user), notice: 'Вопрос удален :('
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def load_question
      @question = Question.find(params[:id])
    end

    def authorize_user
      reject_user unless @question.user == current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      if current_user.present? && params[:question][:user_id].to_i == current_user.id
        params.require(:question).permit(:user_id, :text, :answer)
      else
        params.require(:question).permit(:user_id, :text)
      end
    end

    private

    def check_captcha(model)
      if current_user.present?
        true
      else
        verify_recaptcha(model: model)
      end
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%# Форма для создания/правки вопроса %>
<div class="form">
  <%# Форма для объекта @question %>
  <%= form_for(@question) do |f| %>
    <% if @question.errors.any? %>
      <div class="form-errors">
        <ul>
          <% @question.errors.full_messages.each do |message| %>
            <li class="form-error-message"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%# Скрытое поле — айдишник юзера, кому задается вопрос %>
    <%= f.hidden_field :user_id %>

    <div class="form-field">
      <%= f.label :text, 'Вопрос', class: 'form-label' %>
      <%= f.text_area :text, class: 'form-textarea' %>
    </div>

    <%# Простая авторизация - может ли текущий юзер править вопрос? %>
    <% if current_user.present? && current_user == @question.user %>
      <div class="form-field">
        <%= f.label :answer, 'Ответ', class: 'form-label' %>
        <%= f.text_area :answer, class: 'form-textarea' %>
      </div>
    <% end %>

    <%= recaptcha_tags unless current_user.present?%>

    <div class="form-action buffer-both">
      <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
      или
      <%= link_to "вернуться", user_path(@question.user) %>
    </div>
  <% end %>
</div>

app/views/questions/_question.html.erb
<%# Это фрагмет (паршал, partial) для вывода вопроса. В нем определена %>
<%# локальная переменная question, в которую при вызове будет передан %>
<%# как в метод ruby объект после ключа (object: @question) %>

<% question ||= nil %>
<% action_icon = question.answer.blank? ? 'reply' : 'pencil' %>

<div class="question">
  <div class="question-content">
    <%# Текст вопроса %>
    <div class="question-text text-lead">
      <%= question.text %>
    </div>
    
    <%# Выводим хэштеги у вопроса, если они есть %>  
    <% if find_hashtags(question.text) %>
      <% find_hashtags(question.text).each do |f| %>
        <div class="question-text text-hashtag">
          <%= link_to f, hashtag_path(Hashtag.find_by(text: f)) %> 
        </div>
      <% end %>
    <% end %>    

    <div class="question-date">
      <% if question.author.present? %>
        by <%= link_to "@#{question.author.username}", user_path(question.author) %>
      <% else %>
        by unknown
      <% end %>
    </div>
    
    <%# Текст ответа, если он есть %>
    <% if question.answer.present? %>      
        <div class="question-answer text-lead">
          <%= question.answer %>        
        </div>
        <%# Выводим хэштеги у ответа, если они есть %>
        <% if find_hashtags(question.answer) %>
          <% find_hashtags(question.answer).each do |f| %>
            <div class="question-text text-hashtag">
              <%= link_to f, hashtag_path(Hashtag.find_by(text: f)) %> 
            </div>
          <% end %>
        <% end %>
    <% end %>

    <%# Дата создания вопроса (отформатированная) %>
    <div class="question-date">
      <%= l(question.created_at, format: :short) %>
    </div>
  </div>

  <%# Если адресат вопроса — текущий пользователь, он может редактировать вопрос %>
  <%# и отвечать на него %>
  <% if question.user == current_user %>
    <%# Определяем какая будет иконка, если у вопроса нет ответа, то иконка %>
    <%# овтета на письмо, иначе — карандашик %>
    <% edit_icon = question.answer.blank? ? 'reply' : 'pencil' %>

    <div class="question-actions">
      <%= link_to fa_icon(edit_icon), edit_question_path(question) %>
      <%= link_to fa_icon('trash-o'), question_path(question),
                  method: :delete, data: {confirm: 'Точно удалить вопрос?'} %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<%# Страница редактирования вопроса %>
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Вопрос</h1>

  <div class="column-1-2">
    <%# Подключаем паршиал app/views/questions/_form.html.erb %>
    <%= render 'form' %>
  </div>
</div>