config/routes.rb
Rails.application.routes.draw do

  root "users#index"

  resources :users
  resource :session, only: [:new, :create, :destroy]

  resources :questions, except: [:show, :new, :index]
  resources :hashtags, only: [:show]
end

app/models/user.rb
require 'openssl'

class User < ApplicationRecord
  # параметры работы модуля шифрования паролей
  ITERATIONS = 20000
  DIGEST = OpenSSL::Digest::SHA256.new

  attr_accessor :password

  has_many :questions

  validates :email, :username, presence: true
  validates :email, uniqueness: true

  # перед валидацией переводим username в нижний регистр
  before_validation do
    self.username = username.downcase;

    # присваиваем цвет по умолчанию, если в поле background_color пусто
    self.background_color = "#005a55" if self.background_color.nil?
  end

  # проверка формата email
  validates :email, format: { with: /[\w._%+-]+@[\w.-]+\.[a-zA-Z]{2,4}/ }

  # проверка формата юзернейма пользователя (только латинские буквы, цифры, и знак _) и на уникальность
  validates :username, format: { with: /\A\w+\z/ },
                       uniqueness: { case_sensitive: false }

  # проверка максимальной длинны юзернейма пользователя(не более 40 символов)
  validates :username, length: { maximum: 40 }
  validates_presence_of :password, on: :create
  validates_confirmation_of :password

  # проверка корректного ввода цвета фона в режиме редактирования профиля
  validates :background_color, format: { with: /\A\#[\da-fA-Z]{6}\z/ }

  before_save :encrypt_password

  def encrypt_password
    if self.password.present?
      # создаём т.н. "соль" - рандомная строка, усложняющая задачу хакерам
      self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))

      # создаём хэш пароля - длинная уникальная строка, из которой невозможно установить исходный пароль
      self.password_hash = User.hash_to_string(
          OpenSSL::PKCS5.pbkdf2_hmac(self.password, self.password_salt, ITERATIONS, DIGEST.length, DIGEST)
      )
    end
  end

  # служебный метод, преобразующий бинарную строку в 16-ричный формат, для удобства хранения
  def self.hash_to_string(password_hash)
    password_hash.unpack('H*')[0]
  end

  def self.authenticate(email, password)
    user = find_by(email: email) # сперва находим пользователя по email

    if user.present? && user.password_hash == User.hash_to_string(OpenSSL::PKCS5.pbkdf2_hmac(password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST))
      user
    else
      nil
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, except: [:index, :create, :new]
  before_action :authorize_user, except: [:index, :new, :create, :show]

  def index
    @users = User.all
    @hashtags = Hashtag.all
  end

  def new
    redirect_to root_url, alert: 'Вы уже залогинены' if current_user.present?
    @user = User.new
  end

  def create
    redirect_to root_url, alert: 'Вы уже залогинены' if current_user.present?
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'Вы успешно зарегистрированы'
      session[:user_id] = @user.id # сразу логиним пользователя после регистрации
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'Данные обновлены'
    else
      render 'edit'
    end
  end

  def edit
  end

  def show
    @questions = @user.questions.order(created_at: :desc)

    @new_question = @user.questions.build

    @questions_count = @questions.count
    @answers_count = @questions.where.not(answer: nil).count
    @unanswered_count = @questions_count - @answers_count
  end

  def destroy
    @user.destroy
    flash[:success] = "Пользователь удалён!"
    redirect_to root_path
  end

  private

  def authorize_user
    reject_user unless @user == current_user
  end

  def load_user
    @user ||= User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 :name, :username, :avatar_url, :background_color)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%# Страница редактирования пользователя %>
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Править профиль</h1>

  <div class="column-1-2">
    <%# С помощью специального хелпера form_for мы делаем тег <form ...> %>
    <%# с нужными аттрибутами, после этого в переменной f будет специальный %>
    <%# объект (form builder object), вызывая методы которого мы можем %>
    <%# создавать теги для нужных нам полей формы. %>
    <%= form_for(@user) do |f| %>
      <%# Вывод ошибок валидации пользователя, если есть. Ошибки содержатся %>
      <%# в поле errors модели (в нашем случае @users). %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%# С помощью методов label и text_field у объекта f мы создаем теги %>
      <%# <label ... > и <input type="text" ... > с нужными атрибуами %>
      <div class="form-field">
        <%= f.label :username, class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <%# Поступаем аналогично для других полей %>
      <div class="form-field">
        <%= f.label 'Ваше имя', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'URL вашей аватарки', class: 'form-label' %>
        <%= f.text_field :avatar_url, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'Цвет вашей формы', class: 'form-label' %>
        <%= f.color_field :background_color, class: 'form-color-field' %>
      </div>

      <div class="buffer-top-large buffer-bottom">
        Если не хотите менять пароль — оставьте эти поля пустыми!
      </div>

      <div class="form-field">
        <%= f.label :password, class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action buffer-top">
        <%= f.submit 'Сохранить', class: 'button button-dark button-small button-float-left' %>        
      </div>

      <div class="form-action buffer-top">
        <div class="button button-dark button-small button-float-left button-delete">
          <%= link_to 'Удалить профиль', @user, method: :delete, 
          data: { confirm: "Вы уверены?" } if current_user == @user %>
        </div>
      </div>
    <% end %>

    <%# Подробнее про помощники для создания форм: %>
    <%# http://guides.rubyonrails.org/form_helpers.html %>
  </div>
</div>

app/views/users/index.html.erb
<%# Этот шаблон отрисуется, когда пользователь захочет посмотреть список пользователей %>
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium">Наши пользователи</h1>
  </div>

  <%# Этот код выводит каждого пользователя в цикле %>
  <% @users.each do |user| %>
      <div class="users-list-item">
        <div class="user-image-div user-image-div-small">
          <%# Пользуемся аж тремя хелперами %>
          <%# link_to — генерирует ссылку %>
          <%# image_tag — генерирует картинку %>
          <%# user_avatar — достает из пользователя ссылку на картинку или подставляет дефолтную %>
          <%# Хелпер user_path(user) возвращает относительный путь %>
          <%# страницы пользователя, например /users/1 %>
          <%= link_to image_tag(user_avatar(user), class: 'user-image'), user_path(user) %>
        </div>
      </div>
  <% end %>
  
  <%# Этот код выводит все хэштеги, которые есть в базе %>
  <div class="buffer-top">
    <% @hashtags.each do |hashtag| %>    
        <div class="question-text text-hashtag">
          <%= link_to hashtag.text, hashtag_path(hashtag) %>            
        </div>  
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<%# Страница для регистрации нового пользователя. %>

<%# Обратите внимание, что она очень похожа на страницу редактирования юзера, %>
<%# что позволяет в подобных случаях использовать один и тот же паршиал form %>
<%# в обоих страницах. %>
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Присоединяйся к нам!</h1>

  <div class="column-1-2">
    <%# С помощью специального хелпера form_for мы делаем тег <form ...> %>
    <%# с нужными аттрибутами, после этого в переменной f будет специальный %>
    <%# объект (form builder object), вызывая методы которого мы можем %>
    <%# создавать теги для нужных нам полей формы. %>
    <%= form_for @user do |f| %>
      <%# Вывод ошибок валидации пользователя, если есть. Ошибки содержатся %>
      <%# в поле errors модели (в нашем случае @users). %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%# С помощью методов label и text_field у объекта f мы создаем теги %>
      <%# <label ... > и <input type="text" ... > с нужными атрибуами %>
      <div class="form-field">
        <%= f.label :email, 'Логин (email)', class: 'form-label' %>
        <%= f.text_field :email, class: 'form-text-field' %>
      </div>

      <%# Поступаем аналогично для других полей %>
      <div class="form-field">
        <%= f.label :username, 'Никнейм', class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :name, 'Имя', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password, 'Пароль', class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, 'Пароль ещё раз', class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action">
        <%= f.submit 'Зарегистрироваться', class: 'button button-small button-dark' %>
      </div>
    <% end %>

    <%# Подробнее про помощники для создания форм: %>
    <%# http://guides.rubyonrails.org/form_helpers.html %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-header text-center" style="background-color: <%= @user.background_color %>">
  <h1 class="title-medium">
    <%= @user.name %>
  </h1>

  <div class="buffer-both">
    <%= link_to 'Редактировать профиль', edit_user_path(@user) if current_user == @user %>
  </div> 

  <div class="user-image-div">
    <%= image_tag user_avatar(@user), class: 'user-image', alt: '[Фото]' %>
  </div>

  <h2 class="title-small buffer-both">
    @<%= @user.username %>
  </h2>
</div>

<div class="user-details">
  <div class="user-ask-button container text-center">
    <%= link_to "Спроси меня", '', class: 'button button-light', id: 'ask-button' %>
  </div>

  <%# Выводим счетчики вопросов в три колонки.%>  
  <div class="user-statistics container text-center">
    <div class="column-1-3">
      <h1 class="title-small"><%= @questions_count %></h1>
      <p><%= sklonenie(@questions.count, 'вопрос', 'вопроса', 'вопросов') %></p>
    </div>
    <div class="column-1-3">
      <h1 class="title-small"><%= @answers_count %></h1>
      <p><%= sklonenie(@answers_count, 'ответ', 'ответа', 'ответов') %></p>
    </div>
    <div class="column-1-3">
      <h1 class="title-small"><%= @unanswered_count %></h1>
      <p><%= sklonenie(@unanswered_count, 'безответный', 'безответных', 'безответных') %></p>
    </div>
  </div>
</div>

<div class="user-question-form-div column-1-4 column-1-4-right" id='ask-form'>
  <div class="user-question-form buffer-both">
    <%= form_for @new_question do |f| %>
      <%= f.hidden_field :user_id %>

      <div class="form-field">
        <%= f.label "Ваш вопрос для @#{@user.username}", class: 'form-label' %>
        <%= f.text_area :text, class: 'form-textarea' %>
      </div>

      <%= recaptcha_tags size: 'compact' unless current_user.present?%>

      <div class="form-action">
        <%= submit_tag 'Задать вопрос', class: 'button button-small button-dark' %>
      </div>
    <% end %>
  </div>
</div>

<div class="column-3-4">
  <div class="user-questions buffer-both">
    <div class="questions-list">
      <% @questions.each do |question| %>
        <%= render partial: 'questions/question', object: question %>
      <% end %>
    </div>
  </div>
</div>